# Generated by Django 5.0.1 on 2024-04-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='recipient_name',
            field=models.CharField(default='Unknown Recipient', max_length=100, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='full_address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('city', 'zip_code', 'country', 'recipient_name')},
        ),
    ]
