# Generated by Django 5.0.1 on 2024-04-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shippingaddress_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefan',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computercase',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpuaircooler',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpuliquidcooler',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='harddrive',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='headset',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitor',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouse',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundcard',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ssd',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webcam',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
