# Generated by Django 5.0.1 on 2024-06-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cartitem_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRMING_PAYMENT', 'Confirming Payment'), ('PREPARING', 'Preparing'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('EN_ROUTE', 'En Route'), ('DELIVERED', 'Delivered')], default='CONFIRMING_PAYMENT', max_length=20, verbose_name='Order Status'),
        ),
    ]
