# Generated by Django 5.0.1 on 2024-06-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CREDIT_CARD', 'Credit Card'), ('TRANSFER', 'Transferencia')], default='PAYPAL', max_length=20, verbose_name='Payment Method'),
        ),
    ]
