# Generated by Django 5.0.1 on 2024-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('profile', 'city', 'zip_code', 'country', 'recipient_name')},
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='full_address',
            field=models.CharField(max_length=255),
        ),
    ]
